<?php

// config
define('CMS_DIR', '');
define('RELATIVE_CMS_DIR', '../');
define('PACKAGE_VERSION', '3.0.0');

// options
define('CMS_INSTALL_DATE', 0);
define('FIREBALL_SITEMAP_ENABLE', 1);
define('FIREBALL_REVISION_DELETE', 0);
define('FIREBALL_PAGES_DEFAULT_MENU_ITEM', 1);
define('FIREBALL_PAGES_DEFAULT_ALLOW_INDEXING', 1);
define('FIREBALL_PAGES_DEFAULT_SIDEBAR', 'right');
define('FIREBALL_PAGES_DEFAULT_COMMENTS', 0);
define('FIREBALL_PAGES_DEFAULT_OFFLINE', 0);
define('FIREBALL_PAGES_DEFAULT_ALLOW_SUBSCRIBING', 1);
define('FIREBALL_PAGES_ENABLE_STATISTICS', 1);
define('FIREBALL_PAGES_STATISTICS_DELETE', 0);
define('FIREBALL_CONTENT_SLIDESHOW_INTERVAL', 5000);
