ALTER TABLE cms1_page ADD COLUMN objectTypeID INT(10);
ALTER TABLE cms1_page ADD COLUMN additionalData MEDIUMTEXT DEFAULT NULL;
ALTER TABLE cms1_page ADD FOREIGN KEY (objectTypeID) REFERENCES wcf1_object_type (objectTypeID) ON DELETE CASCADE;
