ALTER TABLE cms1_page ADD COLUMN isDisabled TINYINT(1) DEFAULT 0 AFTER menuItemID;
ALTER TABLE cms1_content ADD COLUMN isDisabled TINYINT(1) DEFAULT 0 AFTER showOrder;

--beta 7 update
ALTER TABLE cms1_page ADD COLUMN stylesheets MEDIUMTEXT AFTER clicks;
ALTER TABLE cms1_page ADD COLUMN authorID INT(10) DEFAULT NULL;
ALTER TABLE cms1_page ADD COLUMN authorName VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE cms1_page ADD COLUMN lastEditorID INT(10) DEFAULT NULL;
ALTER TABLE cms1_page ADD COLUMN lastEditorName VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE cms1_page ADD COLUMN creationTime INT(10) NOT NULL DEFAULT 0;
ALTER TABLE cms1_page ADD COLUMN lastEditTime INT(10) NOT NULL DEFAULT 0;
ALTER TABLE cms1_page ADD COLUMN styleID INT(10) DEFAULT NULL AFTER isCommentable;

ALTER TABLE cms1_page ADD FOREIGN KEY (styleID) REFERENCES wcf1_style (styleID) ON DELETE SET NULL;
ALTER TABLE cms1_page ADD FOREIGN KEY (authorID) REFERENCES wcf1_user (userID) ON DELETE SET NULL;
ALTER TABLE cms1_page ADD FOREIGN KEY (lastEditorID) REFERENCES wcf1_user (userID) ON DELETE SET NULL
