ALTER TABLE cms1_page ADD COLUMN stylesheets MEDIUMTEXT AFTER clicks;
ALTER TABLE cms1_page ADD COLUMN styleID INT(10) DEFAULT NULL AFTER isCommentable;
ALTER TABLE cms1_page ADD COLUMN authorID INT(10) DEFAULT NULL;
ALTER TABLE cms1_page ADD COLUMN authorName VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE cms1_page ADD COLUMN lastEditorID INT(10) DEFAULT NULL;
ALTER TABLE cms1_page ADD COLUMN lastEditorName VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE cms1_page ADD COLUMN creationTime INT(10) NOT NULL DEFAULT 0;
ALTER TABLE cms1_page ADD COLUMN lastEditTime INT(10) NOT NULL DEFAULT 0;
ALTER TABLE cms1_page ADD isPublished TINYINT(1) NOT NULL DEFAULT 1 AFTER isDisabled;
ALTER TABLE cms1_page ADD publicationDate INT(10) NOT NULL DEFAULT 0 AFTER isPublished;
ALTER TABLE cms1_page ADD deactivationDate INT(10) NOT NULL DEFAULT 0 AFTER publicationDate;

ALTER TABLE cms1_counter ADD COLUMN platforms MEDIUMTEXT;
ALTER TABLE cms1_counter ADD COLUMN devices MEDIUMTEXT;
ALTER TABLE cms1_counter CHANGE browsers browsers MEDIUMTEXT;

ALTER TABLE cms1_page ADD FOREIGN KEY (styleID) REFERENCES wcf1_style (styleID) ON DELETE SET NULL;
ALTER TABLE cms1_page ADD FOREIGN KEY (authorID) REFERENCES wcf1_user (userID) ON DELETE SET NULL;
ALTER TABLE cms1_page ADD FOREIGN KEY (lastEditorID) REFERENCES wcf1_user (userID) ON DELETE SET NULL;
