ALTER TABLE cms1_page ADD COLUMN objectTypeID INT(10);
ALTER TABLE cms1_page ADD COLUMN additionalData MEDIUMTEXT DEFAULT NULL;
ALTER TABLE cms1_page ADD FOREIGN KEY (objectTypeID) REFERENCES wcf1_object_type (objectTypeID) ON DELETE CASCADE;

# 2.2.0 Beta 1:
ALTER TABLE cms1_content ADD COLUMN showHeadline TINYINT(1) NOT NULL DEFAULT 0;
ALTER TABLE cms1_file ADD COLUMN width INT(10) NOT NULL DEFAULT 0;
ALTER TABLE cms1_file ADD COLUMN height INT(10) NOT NULL DEFAULT 0;
ALTER TABLE cms1_file ADD COLUMN filesizeThumbnail INT(10) NOT NULL DEFAULT 0;
ALTER TABLE cms1_file ADD COLUMN fileTypeThumbnail VARCHAR(255) NOT NULL DEFAULT '';
ALTER TABLE cms1_file ADD COLUMN widthThumbnail INT(10) NOT NULL DEFAULT 0;
ALTER TABLE cms1_file ADD COLUMN heightThumbnail INT(10) NOT NULL DEFAULT 0;
