
ALTER TABLE cms1_page ADD COLUMN styleID INT(10) DEFAULT NULL AFTER isCommentable;
ALTER TABLE cms1_page ADD FOREIGN KEY (styleID) REFERENCES wcf1_style (styleID) ON DELETE SET NULL;
DROP TABLE IF EXISTS cms1_layout;
